diff --git a/Makefile b/Makefile
index 38531b6..4827275 100644
--- a/Makefile
+++ b/Makefile
@@ -24,7 +24,7 @@ DOCS_DIR = docs
 man:
 	@make -C $(DOCS_DIR) man
 
-install: man
+install: 
 	@echo "Installing RPi-Monitor in ${TARGETDIR}"
 	@mkdir -p ${TARGETDIR}var/lib/rpimonitor
 	@cp -r src/var/lib/rpimonitor/* ${TARGETDIR}var/lib/rpimonitor/
@@ -37,10 +37,6 @@ install: man
 	@mkdir -p ${TARGETDIR}usr/share/rpimonitor
 	@cp -r src/usr/share/rpimonitor/* ${TARGETDIR}usr/share/rpimonitor/
 	@echo "Startup system is ${STARTUPSYS}"
-	@mkdir -p ${TARGETDIR}usr/share/man/man1
-	@cp -r docs/build/man/rpimonitor.1 ${TARGETDIR}usr/share/man/man1/
-	@mkdir -p ${TARGETDIR}usr/share/man/man5
-	@cp -r docs/build/man/rpimonitor-*.conf.5 ${TARGETDIR}usr/share/man/man5/
 	
 ifeq (${STARTUPSYS},sysVinit)
 	@mkdir -p ${TARGETDIR}etc/init.d
