diff --git a/Makefile b/Makefile
index 9042161..5a2e652 100644
--- a/Makefile
+++ b/Makefile
@@ -22,26 +22,29 @@ all:
 install:
 	@echo "Installing RPi-Monitor in ${TARGETDIR}"
 	@mkdir -p ${TARGETDIR}var/lib/rpimonitor
-	@cp -a src/var/lib/rpimonitor/* ${TARGETDIR}var/lib/rpimonitor/
+	@cp -r src/var/lib/rpimonitor/* ${TARGETDIR}var/lib/rpimonitor/
 	@mkdir -p ${TARGETDIR}etc/rpimonitor
-	@cp -a src/etc/rpimonitor/* ${TARGETDIR}etc/rpimonitor/
+	@cp -r src/etc/rpimonitor/* ${TARGETDIR}etc/rpimonitor/
 	@mkdir -p ${TARGETDIR}etc/cron.d
-	@cp -a src/etc/cron.d/* ${TARGETDIR}etc/cron.d/
+	@cp -r src/etc/cron.d/* ${TARGETDIR}etc/cron.d/
 	@mkdir -p ${TARGETDIR}usr/bin
-	@cp -a src/usr/bin/* ${TARGETDIR}usr/bin/
+	@cp -r src/usr/bin/* ${TARGETDIR}usr/bin/
 	@mkdir -p ${TARGETDIR}usr/share/rpimonitor
-	@cp -a src/usr/share/rpimonitor/* ${TARGETDIR}usr/share/rpimonitor/
+	@cp -r src/usr/share/rpimonitor/* ${TARGETDIR}usr/share/rpimonitor/
 	@echo "Startup system is ${STARTUPSYS}"
 ifeq (${STARTUPSYS},sysVinit)
 	@mkdir -p ${TARGETDIR}etc/init.d
-	@cp -a src/etc/init.d/* ${TARGETDIR}etc/init.d/
+	@cp -r src/etc/init.d/* ${TARGETDIR}etc/init.d/
 endif
 ifeq (${STARTUPSYS},upstart)
 	@mkdir -p ${TARGETDIR}etc/init
-	@cp -a src/etc/init/* ${TARGETDIR}etc/init/
+	@cp -r src/etc/init/* ${TARGETDIR}etc/init/
 endif
 ifeq (${STARTUPSYS},systemd)
 	@mkdir -p ${TARGETDIR}usr/lib/systemd/system
-	@cp -a usr/lib/systemd/system/* ${TARGETDIR}etc/init.d/
+	@cp -r usr/lib/systemd/system/* ${TARGETDIR}etc/init.d/
 endif
 	@echo "Installation completed"
+
+clean:
+	@echo
